import numpy as np


def initialize_particles(ann, num_particles):
    """
    Creates an initial population of particles for PSO.
    Each particle is a flat 1D vector encoding all ANN parameters 
    (weights, biases, and activation function indices).
    """
    particles = []

    num_layers = ann.num_layers
    # Number of learnable activation functions (one for each hidden layer)
    num_activation_variables = num_layers - 2 
    num_activation_functions = ann.num_activation_functions
    

    for _ in range(num_particles):
        weights = []
        biases = []
        
        # Initialize weights and biases for all layers
        for i in range(num_layers - 1):
            # Small random weights
            weights.append(np.random.randn(ann.layers[i], ann.layers[i+1]) * 0.1) 
            # Zero biases
            biases.append(np.zeros((1, ann.layers[i+1])))
       
        
        discrete_variable_probabilities = []
        for _ in range(num_activation_variables):
            probability_array = np.random.rand(1, num_activation_functions)
            probability_array /= probability_array.sum()  # Normalize to sum to 1
            discrete_variable_probabilities.append(probability_array.flatten())
            
        discrete_variable_probabilities = np.array(discrete_variable_probabilities)
        
        
        # Generated by ChatGPT
        # --- Flatten and concatenate all into one long vector ---
        flat_vector = np.concatenate(
            [W.flatten() for W in weights] +
            [b.flatten() for b in biases] +
            [discrete_variable_probabilities.flatten()]
        )  
        particles.append(flat_vector)
    
    particles = np.array(particles)
    particle_length = particles.shape[1]
    discrete_variable_length = num_activation_variables * num_activation_functions
    discrete_variable_params = [num_activation_variables, num_activation_functions]
    print(f"Particle Length: {particle_length} (Continuous: {particle_length - discrete_variable_length}, Discrete: {discrete_variable_length})")
    
    return particles, particle_length, discrete_variable_params